--- #
- hosts: ansible_control_host
  gather_facts: no
  become: true
  roles:
    - httpd

- hosts: cluster-kubenetes
  gather_facts: no
  become: true
  roles:
    - nginx
    - minio
    
... #
