apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-configmap
  namespace: nginx-ingress
  labels:
    app: nginx-ingress
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: nginx-ingress
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: nginx-ingress
---
