
---
- name: Install git
  package: name={{item}} state=present update_cache=true
  with_items:
    - git
    - htop
  register: Output
  always:
    - debug: 
        msg: 
          - "Conteudo da mensagem : {{Output}}"
          - "Conteudo da mensagem - {{Output.changed}}"

- name: Install a list of packages
  apt:
    name:
      - httpd
    state: present

