apiVersion: v1
kind: Service
metadata:
  name: uspr-service
  namespace: uspr
spec: 
  ports:
  - port: 8787
    targetPort: 8787
    protocol: TCP
    name: uspr
  selector:
    app: uspr
  type: ClusterIP
  